Web_Python/Main_Project/main_project/main_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('quotes.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Web_Python/Main_Project/main_project/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quote'

urlpatterns = [
    path('', views.QuoteView.as_view(), name='index'),
    path('quotes/add/', views.QuoteView.as_view(), name='add-quote'),
    path('quotes/scrape/', views.QuoteView.as_view(), name='scrape-quotes'),
    path('quotes/edit/<int:pk>', views.QuoteUpdateView.as_view(), name='edit'),
    path('quotes/remove/<int:pk>', views.QuoteRemoveView.as_view(), name='remove'),
    path('tag/<str:tag>', views.QuoteView.as_view(), name='search-tag'),
    path('tag/add/', views.TagView.as_view(), name='add-tags'),
    path('author/<str:author>', views.AuthorView.as_view(), name='author'),
    path('author/add/', views.AuthorView.as_view(), name='add-author'),
    path('author/edit/<int:pk>', views.AuthorUpdateView.as_view(), name='edit-author'),
    path('example_fill_db', views.example_fill_db, name='example-fill-db'),
]

Web_Python/Main_Project/main_project/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from django.urls import path

from users.forms import LoginForm
from users.views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path(
        "register/",
        RegisterView.as_view(template_name="users/register.html"),
        name="register",
    ),
    path(
        "login/",
        LoginView.as_view(
            redirect_authenticated_user=True,
            template_name="users/login.html",
            authentication_form=LoginForm,
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"
    ),
    # path("profile/", views.profile, name="profile"),
    path("reset-password/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

Web_Python/Main_Project/main_project/quotes/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True, null=False, blank=False)

    def __str__(self):
        return self.name


# Create your models here.
class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, help_text="The user who created the quote", related_name='author_related')
    fullname = models.CharField(max_length=255, blank=False)
    born_date = models.CharField(max_length=100, blank=False)
    born_location = models.CharField(max_length=255, blank=False)
    description = models.TextField(blank=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'fullname'], name='unique_author_constraint')
        ]

    def __str__(self):
        return self.fullname


class Quote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, related_name='quote_related')
    quote = models.TextField(null=False, blank=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='quotes', blank=False)
    tags = models.ManyToManyField(Tag, blank=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'quote'], name='unique_quote_constraint')
        ]

    def __str__(self):
        return self.quote

Web_Python/Main_Project/main_project/quotes/forms.py
from datetime import datetime
from django import forms

from django.forms import (
    ModelForm,
    CharField,
    TextInput,
    ModelChoiceField,
    ModelMultipleChoiceField,
)

from quotes.models import (
    Tag,
    Author,
    Quote,
    User,
)


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class QuoteForm(ModelForm):
    author = ModelChoiceField(queryset=Author.objects.none())  # noqa
    tags = ModelMultipleChoiceField(queryset=Tag.objects.none())  # noqa

    class Meta:
        model = Quote
        fields = ['quote', 'author', 'tags']

    def __init__(self, user: User, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['author'].queryset = Author.objects.filter(user=user)  # noqa
        self.fields['tags'].queryset = Tag.objects.all()  # noqa


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ['fullname', 'born_date', 'born_location', 'description']
        
    def clean_born_date(self):
        born_date = self.cleaned_data.get('born_date')

        # Check if the birth date is in the future
        if born_date and born_date > datetime.date.today():
            raise forms.ValidationError("Дата народження не може бути у майбутньому.")

        return born_date

Web_Python/Main_Project/main_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db import IntegrityError
from django.db.models import Count
from django.http import Http404
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, DeleteView, View

from quotes.forms import QuoteForm, TagForm, AuthorForm
from quotes.models import Tag, Author, Quote
from quotes.service.scrape_quotes import scrape_quotes


class AuthorUpdateView(UpdateView):
    model = Author
    fields = ['fullname', 'born_date', 'born_location', 'description']
    template_name = 'quote/edit_author.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        return reverse_lazy('quote:author', kwargs={'author': self.object.fullname})


class QuoteUpdateView(UpdateView):
    model = Quote
    fields = ['quote', 'author', 'tags']
    success_url = reverse_lazy('quote:index')
    template_name = 'quote/edit_quote.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return self.success_url


class QuoteRemoveView(DeleteView):
    model = Quote
    success_url = reverse_lazy('quote:index')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        return obj if obj.user == self.request.user else Http404()

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url

        return redirect('quote:index')


class QuoteView(View):
    quotes_per_page = 10
    template_get = 'quote/quotes.html'
    template_add = 'quote/add_quote.html'
    form_class = QuoteForm
    model = Quote

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET':
            if 'add' in request.path:
                return self.get_form(request)
            elif 'scrape' in request.path:
                return self.scrape(request)

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, **kwargs):
        match kwargs:
            case {'tag': tag}:
                quotes = self.model.objects.filter(tags__name=tag).order_by('-id')  # noqa
            case _:
                quotes = self.model.objects.all().order_by('-id')  # noqa

        top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]  # noqa

        paginator = Paginator(quotes, self.quotes_per_page)

        context = {
            'page_obj': paginator.get_page(request.GET.get('page')),
            'user': request.user,
            'top_tags': top_tags,
            'by_tag': kwargs.get('tag'),
        }
        return render(request, self.template_get, context)

    @method_decorator(login_required)
    def scrape(self, request):
        scrape_quotes(request.user)
        return redirect('quote:index')

    @method_decorator(login_required)
    def get_form(self, request):
        return render(request, self.template_add, {'form': self.form_class(request.user)})

    @method_decorator(login_required)
    def post(self, request):
        form = self.form_class(request.user, request.POST)

        if not form.is_valid():
            return render(request, self.template_add, {'form': form})

        try:
            new_quote = form.save(commit=False)
            new_quote.user = request.user

            new_quote.save()
            form.save_m2m()

        except IntegrityError as e:
            if 'unique constraint "quote of username"' in str(e):
                form.add_error('quote', "This quote already exists. Please add a new quote.")

            return render(request, self.template_add, {'form': form})

        return redirect('quote:index')


class AuthorView(View):
    template_get = 'quote/author.html'
    template_add = 'quote/add_author.html'
    form_class = AuthorForm
    model = Author

    def dispatch(self, request, *args, **kwargs):
        if request.method == 'GET' and 'add' in request.path:
            return self.get_form(request)

        return super().dispatch(request, *args, **kwargs)

    def get(self, request, author: str):
        context = {
            "author": self.model.objects.get(fullname=author),  # noqa
            "user": request.user,
        }
        return render(request, self.template_get, context)

    @method_decorator(login_required)
    def get_form(self, request):
        return render(request, self.template_add, {'form': self.form_class()})

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)

        if not form.is_valid():
            return render(request, self.template_add, {'form': form})

        try:
            new_author = form.save(commit=False)
            new_author.user = request.user
            new_author.save()
        except IntegrityError as e:
            if 'unique constraint "author of username"' in str(e):
                form.add_error("fullname", "Error!!!")

            return render(request, self.template_add, {'form': form})

        return redirect(to='quote:index')


class TagView(View):
    template_name = 'quote/add_tags.html'
    form_class = TagForm
    model = Tag

    @method_decorator(login_required)
    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class()})

    @method_decorator(login_required)
    def post(self, request):
        form = self.form_class(request.POST)

        if not form.is_valid():
            return render(request, self.template_name, {'form': form})

        tag = form.save(commit=False)
        tag.user = request.user
        tag.save()
        return redirect(to='quote:index')


@login_required
def example_fill_db(request):
    author, _ = Author.objects.get_or_create(
        user=request.user,
        fullname='fullname',
        defaults={
            'born_date': 'born_date',
            'born_location': 'born_location',
            'description': 'description',
        }
    )
    tag, _ = Tag.objects.get_or_create(name='Test name')
    quote, _ = Quote.objects.get_or_create(
        user=request.user,
        quote='lorem ipsum',
        defaults={
            'author': author
        }
    )
    quote.tags.add(tag)
    return redirect(to='quote:index')

Web_Python/Main_Project/main_project/quotes/templates/quote/add_author.html
{% extends "quote/base.html" %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'quote:add-author' %}">
        {% csrf_token %}
        <div class="form-group">
            <label> Author full name:
                {{ form.fullname }}
            </label>
            <span>{{ form.errors.fullname }}</span>
        </div>
        <div class="form-group">
            <label>Born date:
                {{ form.born_date }}
            </label>
            <span>{{ form.errors.born_date }}</span>
        </div>
        <div class="form-group">
            <label> Born location:
                {{ form.born_location }}
            </label>
            <span>{{ form.errors.born_location }}</span>
        </div>
        <label> Description:</label>
        <div class="form-group">
<!--            <label> Description:-->
                {{ form.description }}
<!--            </label>-->
            <span>{{ form.errors.description }}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/add_quote.html
{% extends "quote/base.html" %}

{% block content %}

<div class="container">
    <form method="post" class="form">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
        <a href="{% url 'quote:scrape-quotes' %}" class="btn btn-link float-right">Scrape from http://quotes.toscrape.com</a>
    </form>
</div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/add_tags.html
{% extends "quote/base.html" %}

{% block content %}

<div class="container">
    <form method="POST" action="{% url 'quote:add-tags' %}">
        {% csrf_token %}
        <div class="form-group">
            <label>Enter the tag name:
                {{form.name}}
            </label>
            <span>{{ form.errors.name }}</span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/author.html
{% extends 'quote/base.html' %}

{% block title %}{{ author.fullname }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p><strong>Born:</strong>
          <span class="author-born-date">{{ author.born_date }}</span>
          <span class="author-born-location">{{ author.born_location }}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">
            {{ author.description }}
        </div>
        {% if user.id == author.user_id %}
            <div class="quote-actions mt-3">
                <a href="{% url 'quote:edit-author' author.pk %}" class="btn btn-warning mr-2">Edit</a>
            </div>
        {% endif %}
    </div>
  </div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/base.html
<!-- base.html -->
<!DOCTYPE html>
{% load bootstrap4 %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}My quotes!{% endblock %}</title>
  {% bootstrap_css %}
  {% load static %}
  <link rel="stylesheet" href="{% static 'quote/main.css' %}">
</head>
<body>
  <header>
    <h1>Quotes</h1>
    <nav>
      <ul class="nav-left">
        <li><a href="/">Quotes</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'quote:add-quote' %}">Add quote</a></li>
          <li><a href="{% url 'quote:add-author' %}">Add author</a></li>
          <li><a href="{% url 'quote:add-tags' %}">Add tags</a></li>
          <li><a href="{% url 'quote:example-fill-db' %}">Non Form Example</a></li>
        {% endif %}
      </ul>
      <ul class="nav-right">
        {% if user.is_authenticated %}
          <li><a href="{% url 'users:logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'users:register' %}">Create account</a></li>
          <li><a href="{% url 'users:login' %}">Login</a></li>
        {% endif %}
      </ul>
    </nav>
  </header>
    {% block content %}
    {% endblock %}
</body>
</html>

Web_Python/Main_Project/main_project/quotes/templates/quote/edit_author.html
{% extends 'quote/base.html' %}

{% block title %}
Edit Author - {{ object.author }}
{% endblock %}

{% block content %}
  <div class="container">
    <h2>Edit Author</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/edit_quote.html
{% extends 'quote/base.html' %}

{% block title %}
Edit Quote - {{ object.quote }}
{% endblock %}

{% block content %}
  <div class="container">
    <h2>Edit Quote</h2>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Save</button>
    </form>
  </div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/quote_confirm_delete.html
{% extends 'quote/base.html' %}

{% block title %}Delete quote{% endblock %}

{% block content %}
  <div class="container">
    <h2>Delete quote</h2>
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete <b><i>“{{object.quote}}”</i></b>?</p>
      <button type="submit" class="btn btn-danger">Delete</button>
      <a href="{% url 'quote:index' %}" class="btn btn-secondary">Cancel</a>
    </form>
  </div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/quotes.html
{% extends 'quote/base.html' %}

{% block title %}
Quotes
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h1 class="my-4">Quotes</h1>
            {% if by_tag %}
            <h3>Viewing tag: <a href="{% url 'quote:search-tag' by_tag %}">{{ by_tag }}</a></h3>
            {% endif %}
            <ul class="list-group quote-list">
                {% for quote in page_obj %}
                <li class="list-group-item quote-item">
                    <div class="quote-text"><i>“{{ quote.quote }}”</i></div>
                    <div class="quote-author">by
                        <a href="{% url 'quote:author' quote.author %}"><b>{{ quote.author }}</b></a>
                    </div>
                    <div class="quote-tags">
                        <small>Tags:</small>
                        {% for tag in quote.tags.all %}
                        <span class="badge badge-pill badge-sm badge-warning">
                        <a href="{% url 'quote:search-tag' tag.name %}"><i>{{ tag.name }}</i></a>
                      </span>
                        {% empty %}
                        <span class="badge badge-pill badge-sm badge-warning">
                        ---
                      </span>
                        {% endfor %}
                    </div>
                    {% if user == quote.user %}
                    <div class="quote-actions mt-3">
                        <a href="{% url 'quote:edit' quote.id %}?next={{ request.path }}{% if page_obj.has_previous or page_obj.has_next %}?page={{ page_obj.number }}{% endif %}"
                           class="btn btn-warning mr-2">Edit</a>
                        <a href="{% url 'quote:remove' quote.id %}?next={{ request.path }}{% if page_obj.has_previous or page_obj.has_next %}?page={{ page_obj.number }}{% endif %}"
                           class="btn btn-danger">Delete</a>
                    </div>
                    {% endif %}
                </li>
                {% empty %}
                <li class="list-group-item">No quotes found.</li>
                {% endfor %}
            </ul>

            {% if page_obj.has_previous or page_obj.has_next %}
            <nav>
                <ul class="nav-left">
                    {% if page_obj.has_previous %}
                    <li class="previous">
                        <a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">←</span>
                            Previous</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav-right">
                    {% if page_obj.has_next %}
                    <li class="next ml-auto">
                        <a href="?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
        </div>
        <div class="col-md-4">
            <h2>Top Ten tags</h2>
            <ol>
                {% for tag in top_tags %}
                <li>
                    <a href="{% url 'quote:search-tag' tag.name %}">{{ tag.name }}</a>
                </li>
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock %}

Web_Python/Main_Project/main_project/quotes/templates/quote/search_tag.html
{% extends 'quote/base.html' %}

{% block title %}My quotes!{% endblock %}

{% block content %}
  <div class="container">
    <h2>Quotes filter by tag <b>{{tag}}</b></h2>
    <ul class="quote-list">
      {% for quote in quotes %}
        <li class="quote-item">
          <div class="quote-text">“{{ quote.quote }}”</div>
          <div class="quote-author">by {{ quote.author }}</div>
          <div class="quote-tags">
            {% for tag in quote.tags.all %}
              <span class="tag"><a href="tag/{{ tag.name }}">#{{ tag.name }}</a></href></span>
            {% endfor %}
          </div>
        </li>
      {% empty %}
        <li>No quotes found.</li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

<link rel="stylesheet" href="{% static 'quote/styles.css' %}">