PersonalAssistant/PersonalAssistant/Notes/urls.py
from django.urls import path
from . import views



# def fake_login(request):
#     return HttpResponse("Fake login page. No actual login functionality.")


app_name = "notes"


urlpatterns = [
    path("", views.main, name="index"),
    path(
        "add/", views.NoteView.as_view(), name="add-note"
    ),  # изменил "add-quote" на "add-note" для ясности
    path("edit/<int:pk>", views.NoteUpdateView.as_view(), name="edit"),
    path("remove/<int:pk>", views.NoteRemoveView.as_view(), name="remove"),
    path(
        "search/", views.NoteSearchView.as_view(), name="search-notes"
    ),  # новый путь для поиска
    # path(
    #     "tag/<str:tag>", views.NoteSearchView.as_view(), name="search-tags"
    # ),  # этот путь может быть не нужен, так как мы используем POST для поиска
    path("add-tag/", views.TagView.as_view(), name="add-tags"),
]

PersonalAssistant/PersonalAssistant/PersonalAssistant/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('utils/', include('Utils.urls')),
    path('', include('Contacts.urls')),
    path('', include('Users.urls')),
    path("notes/", include("Notes.urls", namespace="notes")),
]

PersonalAssistant/PersonalAssistant/Utils/urls.py
from django.urls import path
from . import views


app_name = 'utils'

urlpatterns = [
    path('upload_files/', views.upload_files, name="upload"),
    path('images/', views.show_user_images, name="show_images"),
    path('documents/', views.show_user_documents, name="show_documents"),
    path('unknown/', views.show_user_unknown, name="show_unknown"),
    path('download/<int:file_id>', views.download_user_file, name="download"),
    path('delete/<int:file_id>', views.remove_user_file, name="delete"),
    path('authorize/', views.dropbox_oauth, name='dropbox_oauth'),
    path('authorized/', views.dropbox_authorized, name='dropbox_authorized'),
    path('weather/', views.weather_forcast, name="get_weather"),
    path('utils_main_page/', views.main_page, name='main_page')
]

PersonalAssistant/PersonalAssistant/Utils/models.py
from django.db import models
from django.db.models import ForeignKey
from django.contrib.auth.models import User

class UploadedUserFiles(models.Model):
    href = models.CharField(max_length=1000, blank=True, null=True)
    type = models.CharField(max_length=1000, blank=True, null=True)
    category = models.CharField(max_length=1000, blank=True, null=True)
    file_id = models.CharField(max_length=1000, blank=True, null=True, default=None)
    user = ForeignKey(User, on_delete=models.CASCADE)
    dbx = models.CharField(max_length=1000, blank=True, null=True, default=None)

PersonalAssistant/PersonalAssistant/Utils/views.py
import os
import json
import dropbox
import cloudinary.uploader
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, HttpResponse

from dotenv import load_dotenv

from .models import UploadedUserFiles


import requests
from django.http import JsonResponse, FileResponse, HttpResponse
from ipware import get_client_ip

from datetime import datetime

load_dotenv()

DROPBOX_APP_KEY = os.environ.get("DROPBOX_APP_KEY")
DROPBOX_APP_SECRET = os.environ.get("DROPBOX_APP_SECRET")
REDIRECT_URL = 'https://personalassistant.fly.dev/utils/'

cloudinary.config(
  cloud_name=os.environ.get('cloud_name'),
  api_key=os.environ.get('api_key'),
  api_secret=os.environ.get('api_secret')
)

extensions = {'Images': ['jpeg', 'png', 'jpg', 'svg'],
              "Documents": ['doc', 'docx', 'txt', 'pdf', 'xlsx', 'pptx'],
              "Unknown": []}

access_token = os.environ.get('ACCESS_TOKEN')


def main_page(request):
    return render(request, 'Utils/main_page.html')


def get_current_datetime_string():
    current_datetime = datetime.now()
    return current_datetime.strftime("%Y-%m-%d--%H-%M-%S__")


def check_time_difference(datetime_str, path):
    current_datetime = datetime.now()
    provided_datetime = datetime.strptime(datetime_str, "%Y-%m-%d--%H-%M-%S")
    time_difference = current_datetime - provided_datetime
    if time_difference.total_seconds() > 60:
        os.remove(path)
        return "clear"
    return None


def check_extensions(file):
    extns = file.split('.')[-1]
    for key, value in extensions.items():
        if extns in value:
            return key
    return "Unknown"


def create_dropbox_folders(request, user_id):
    dbx = get_access_dbx(request)
    user_1_folder_path = f'/User_{user_id}'
    try:
        dbx.files_create_folder(user_1_folder_path)
        cloudinary.api.create_folder(f'User_{user_id}')
        print(f'Створено папку {user_1_folder_path}')
    except dropbox.exceptions.ApiError as e:
        print(f'Помилка при створенні папки {user_1_folder_path}: {e}')


@login_required
def upload_files(request):

    if request.method == 'POST':
        uploaded_file = request.FILES['file']

        if uploaded_file.size > 128 * 1024 * 1024:
            return HttpResponse("The file is larger than 128 MB. Downloading is not allowed.")

        fs = FileSystemStorage()
        fs.save(f'Utils/files_to_upload/{uploaded_file}', uploaded_file)
        full_path2 = os.path.join(os.getcwd(), 'Utils')
        full_path3 = os.path.join(full_path2, "files_to_upload")
        for file in os.listdir(full_path3):
            file_path = os.path.join(full_path3, file)
            result = check_extensions(file)
            try:
                fi = 'None'
                user = User.objects.get(username=request.user)
                if result == 'Images':
                    folder_path = f'user_{request.user.id}/Images'
                    path = os.path.join(os.getcwd(), "Utils")
                    path = os.path.join(path, "files_to_upload")
                    upload = cloudinary.uploader.upload(os.path.join(path, file), folder=folder_path)
                    file_url = upload["secure_url"]
                    file_id = upload["public_id"]
                    fi = file_id
                    user_file = UploadedUserFiles(href=file_url, type=file, category=result,file_id=file_id, user=user)
                    user_file.save()
                with open(file_path, 'rb') as f:
                    dbx = get_access_dbx(request)
                    folder_path = f'user_{user.id}/{result}'
                    dbx_file = dbx.files_upload(f.read(), f'/{folder_path}/{file}')
                public_url = dbx.sharing_create_shared_link_with_settings(path=dbx_file.path_display)
                try:
                    file_get = UploadedUserFiles.objects.get(file_id=fi)
                    if file_get:
                        file_get.dbx = f'/User_{request.user.id}/{result}/{file}'
                        file_get.save()
                        os.remove(file_path)
                        return redirect('/base')
                except:
                    print('EMPTY!')
                user_file = UploadedUserFiles(href=public_url.url, type=file, category=result, user=user)
                user_file.save()
                os.remove(file_path)
                return redirect('/base')
            except Exception as e:
                print(e)
    return render(request, 'Utils/upload_files.html')


@login_required
def show_user_images(request):
    user_images = UploadedUserFiles.objects.filter(user_id=request.user.id, category='Images')
    context = {'user_images': user_images}
    return render(request, 'Utils/show_images.html', context)


@login_required
def show_user_documents(request):
    user_documents = UploadedUserFiles.objects.filter(user_id=request.user.id, category='Documents')
    context = {'user_documents': user_documents}
    return render(request, 'Utils/show_documents.html', context)


@login_required
def show_user_unknown(request):
    user_files = UploadedUserFiles.objects.filter(user_id=request.user.id, category='Unknown')
    context = {'user_files': user_files}
    return render(request, 'Utils/show_else.html', context)


@login_required
def remove_user_file(request, file_id):
        dbx = get_access_dbx(request)
        print(dbx)
        file = UploadedUserFiles.objects.get(id=file_id)
        category = file.category
        path = f'/User_{file.user_id}/{file.category}/{file.type}'
        print(path)
        try:
            dbx.files_delete_v2(f'/User_{file.user_id}/{file.category}/{file.type}')
        except Exception as e:
            print(e)
        file.delete()
        if category == "Images":
            return redirect('utils:show_images')
        elif category == "Documents":
            return redirect('utils:show_documents')
        else:
            return redirect('utils:show_unknown')


@login_required
def download_user_file(request, file_id):
    dbx = get_access_dbx(request)
    file = UploadedUserFiles.objects.get(id=file_id)
    if file.dbx:
        dropbox_file_path = file.dbx
    else:
        dropbox_file_path = (f'/User_{file.user_id}/{file.category}/{file.type}')
    path = os.path.join(os.getcwd(), 'Utils')
    local_file_path = os.path.join(path, "downloaded")
    for fil in os.listdir(local_file_path):
        res = fil.split('__')[0]
        check_time_difference(res, os.path.join(local_file_path, fil))
    if not os.path.exists(local_file_path):
        os.makedirs(local_file_path)
        print('Folder not exist')
    else:
        metadata, res = dbx.files_download(dropbox_file_path)
        new_name = get_current_datetime_string()+metadata.name
        with open(f'{local_file_path}/{new_name}', 'wb') as f:
            f.write(res.content)
    file_path = f'{local_file_path}/{new_name}'
    response = FileResponse(open(file_path, 'rb'))
    response['Content-Disposition'] = f'attachment; filename="{file.type}"'
    return response


def dropbox_oauth(request):
    print('!!!!!!Auth Started !!!!!!!!!!!')
    return redirect(f'https://www.dropbox.com/oauth2/authorize?client_id={DROPBOX_APP_KEY}&redirect_uri={REDIRECT_URL}authorized&response_type=code')


def get_access_token():
    with open('OAuth_token.json', 'r') as file:
        data = json.load(file)
        date = data.get('datetime')
        date_dt_obj = datetime.strptime(date, "%Y-%m-%d %H:%M")
        curent_time = datetime.now()
        delta = ((curent_time - date_dt_obj).total_seconds()) / 60 / 60
        print(delta)
        if delta > 3:
            return None
        token = data.get('token')
        print(date, token)
        return token


def get_access_dbx(request):
    dbx = None
    try:
        access_token = get_access_token()
        if access_token:
            dbx = dropbox.Dropbox(access_token)
        else:
            print("Try refresh!!!!!!!!!!!!")
            return redirect(to="utils:dropbox_oauth")
    except Exception as err:
        print(f"My ERROR !!!!! ::: {err}")

    return dbx


def dropbox_authorized(request):
    try:
        code = request.GET["code"]
        print(f"Code: {code}")
    except KeyError:
        return JsonResponse({"error": "Authorization code not found in the request."}, status=400)
    data = requests.post('https://api.dropboxapi.com/oauth2/token', {
        "code": code,
        "grant_type": "authorization_code",
        "redirect_uri": f"{REDIRECT_URL}authorized",
    }, auth=(DROPBOX_APP_KEY, DROPBOX_APP_SECRET))
    request.session["DROPBOX_ACCESS_TOKEN"] = data.json()["access_token"]
    with open('OAuth_token.json', 'w') as file:
        json.dump({"datetime": datetime.now().strftime("%Y-%m-%d %H:%M"), "token": data.json()["access_token"]}, file, indent=4, ensure_ascii=False)

    return redirect(to="/base")
  

def get_day_of_week(date_str):
    date_obj = datetime.strptime(date_str, '%Y-%m-%d')

    return date_obj.strftime('%A')


def weather_forcast(request):
    api_key = os.environ.get('API_WEATHER')
    client_ip, is_routable = get_client_ip(request)
    api = os.environ.get('API_IPSTACK')
    if client_ip:
        request_url = f'http://api.ipstack.com/{client_ip}?access_key={api}'
        response = requests.get(request_url)
        result = response.content.decode()
        result = json.loads(result)
        if response:
            city = result.get('city')
            url = f'https://api.weatherbit.io/v2.0/forecast/daily?city={city}&key={api_key}'
            try:
                data = requests.get(url).json()
                weather_data = data['data']

                for entry in weather_data:
                    entry['day_of_week'] = get_day_of_week(entry['valid_date'])

                context = {'city': city, 'weather_data': weather_data}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/main_page.html
{% extends "Contacts/base.html" %}

{% block content %}
<div class="text-center mt-1 mb-3">
    <a href="{% url 'utils:upload' %}" class="btn btn-primary">Upload file</a>
</div>
    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'utils:show_unknown' %}">
      <div class="card-body">
        <h5 class="card-title">Unknown Extensions</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">Another</h6>
        <p class="card-text">A file with UNKNOWN filename extension</p>
      </div>
      </a>
    </div>
    <br>

    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'utils:show_images' %}">
      <div class="card-body">
        <h5 class="card-title">Images</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">Pictures</h6>
        <p class="card-text">Edit and delete pictures</p>
      </div>
      </a>
    </div>

    <br>
    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'utils:show_documents' %}">
      <div class="card-body">
        <h5 class="card-title">Documents</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">Documents</h6>
        <p class="card-text">Your documents</p>
      </div>
      </a>
    </div>

{% endblock %}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/show_documents.html
{% extends "Contacts/base.html" %}
{% load static %}
{% block content %}
    <style>
        .document-block {
            max-width: 300px; /* Максимальная ширина блока */
            border: 1px solid #ccc;
            border-radius: 5px;
            padding: 20px;
            margin: 10px;
            display: flex;
            flex-direction: column;
            align-items: center;
            text-align: center;
        }

        .document-block img {
            width: 178px;
            margin-bottom: 10px;
        }

        .contrast {
            display: inline-block;
            padding: 10px 15px;
            margin: 5px;
            border: 1px solid #007bff;
            border-radius: 5px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .contrast:hover {
            background-color: #0056b3;
        }
    </style>
    <h2>Documents list:</h2>
    {% for document in user_documents %}
    <div class="document-block">
        <h3>{{ document.type }}</h3>
        <a href="{{ document.href }}"><img src="{% static 'Utils/images/document_image.jpg' %}" alt="Картинка" class="img-responsive" width="178px"></a>
        <a href="{% url 'utils:delete' document.id %}" role="button" class="contrast"> Delete </a>
        <a href="{% url 'utils:download' document.id %}" role="button" class="contrast"> Download</a>
    </div>
    {% endfor %}
{% endblock %}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/show_else.html
{% extends "Contacts/base.html" %}
{% load static %}
{% block content %}
<style>
    .document-block {
        max-width: 300px; /* Максимальная ширина блока */
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 20px;
        margin: 10px;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
    }

    .document-block img {
        width: 178px;
        margin-bottom: 10px;
    }

    .contrast {
        display: inline-block;
        padding: 10px 15px;
        margin: 5px;
        border: 1px solid #007bff;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .contrast:hover {
        background-color: #0056b3;
    }
</style>

<h2>Another files list:</h2>
{% for unknown in user_files %}
<div class="document-block">
    <h3>{{ unknown.type }}</h3>
    <a href="{{ unknown.href }}"><img src="{% static 'Utils/images/archive_image.jpg' %}" alt="Картинка" class="img-responsive" width="178px"></a>
    <a href="{% url 'utils:delete' unknown.id %}" role="button" class="contrast">Delete</a>
    <a href="{% url 'utils:download' unknown.id %}" role="button" class="contrast">Download</a>
</div>
{% endfor %}
{% endblock %}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/show_images.html
{% extends "Contacts/base.html" %}
{% load static %}
{% block content %}
<style>
    .image-card {
        max-width: 300px; /* Максимальная ширина карточки */
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 10px;
        margin: 10px;
        display: flex;
        flex-direction: column;
        align-items: center;
        text-align: center;
    }

    .image-card img {
        width: 178px;
        margin-bottom: 10px;
    }

    .button-container {
        display: flex;
        justify-content: space-around;
        width: 100%;
    }

    .button-container a {
        padding: 10px 15px;
        border: 1px solid #007bff;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .button-container a:hover {
        background-color: #0056b3;
    }
</style>

<h2>Images list:</h2>
{% for image in user_images %}
    <div class="image-card">
        <a href="{{ image.href }}"><img src="{{ image.href }}" alt="image" class="img-responsive" width="178px"></a>
        <div class="button-container">
            <a href="{% url 'utils:delete' image.id %}" role="button">Delete</a>
            <a href="{% url 'utils:download' image.id %}" role="button">Download</a>
        </div>
    </div>
{% endfor %}
{% endblock %}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/upload_files.html
{% extends "Contacts/base.html" %}

{% block content %}
<div class="container">
    <h2>Завантажити файл</h2>
    <form method="post" enctype="multipart/form-data" action="{% url 'utils:upload' %}">
        {% csrf_token %}
        <div class="form-group mb-2">
            <label for="file">Choose file:</label>
            <input type="file" name="file" id="file">
        </div>
        <button type="submit" class="btn btn-primary">Upload</button>
    </form>
</div>
{% endblock %}

PersonalAssistant/PersonalAssistant/Utils/templates/Utils/weather.html
{% extends "Contacts/base.html" %}

{% block content %}
    <h1 class="text-center">Weather in {{ city }}</h1>

    <div class="row">
        {% for weather_entry in weather_data|slice:":8" %}
            <div class="col-md-3 {% if forloop.last %}mr-3{% endif %}">
                <div class="card mb-4">
                    <div class="card-body">
                        <h5 class="card-title">{{ weather_entry.day_of_week }}</h5>
                        <p class="card-text">Temperature: {{ weather_entry.temp }}°C</p>
                        <p class="card-text">Wind speed: {{ weather_entry.wind_spd }} м/с</p>
                        <p class="card-text">Description: {{ weather_entry.weather.description }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% if status %}
        <p>Статус: {{ status }}</p>
    {% endif %}
{% endblock %}