PersonalAssistant/PersonalAssistant/Contacts/urls.py
from django.urls import path

from .views import start_page
from . import views
from .views import add_contact
from .views import contact_search
from .views import edit_contact
from .views import delete_contact
from .views import contact_list


app_name = 'contacts'

urlpatterns = [
    path('base/', start_page, name="start_page"),
    path('add_contact/', add_contact, name='add_contact'),
    path('contact_search/', contact_search, name='contact_search'),
    path('edit_contact/<int:contact_id>/', edit_contact, name='edit_contact'),
    path('delete_contact/<int:contact_id>/', delete_contact, name='delete_contact'),
    path('contacts/', contact_list, name='contact_list'),
    path('contact_search/', views.contact_search, name='contact_search'),
    path('feedback/', views.send_feedback, name='send_feedback'),
    path('feedback/success/', views.feedback_success, name='feedback_success'),
]

PersonalAssistant/PersonalAssistant/Notes/urls.py
from django.urls import path
from . import views



# def fake_login(request):
#     return HttpResponse("Fake login page. No actual login functionality.")


app_name = "notes"


urlpatterns = [
    path("", views.main, name="index"),
    path(
        "add/", views.NoteView.as_view(), name="add-note"
    ),  # изменил "add-quote" на "add-note" для ясности
    path("edit/<int:pk>", views.NoteUpdateView.as_view(), name="edit"),
    path("remove/<int:pk>", views.NoteRemoveView.as_view(), name="remove"),
    path(
        "search/", views.NoteSearchView.as_view(), name="search-notes"
    ),  # новый путь для поиска
    # path(
    #     "tag/<str:tag>", views.NoteSearchView.as_view(), name="search-tags"
    # ),  # этот путь может быть не нужен, так как мы используем POST для поиска
    path("add-tag/", views.TagView.as_view(), name="add-tags"),
]

PersonalAssistant/PersonalAssistant/PersonalAssistant/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('utils/', include('Utils.urls')),
    path('', include('Contacts.urls')),
    path('', include('Users.urls')),
    path("notes/", include("Notes.urls", namespace="notes")),
]

PersonalAssistant/PersonalAssistant/Users/urls.py
from django.urls import path
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('', views.main_page, name='main_page'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='Users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='Users/password_reset_confirm.html',
                                          success_url='/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='Users/password_reset_complete.html'),
         name='password_reset_complete'),

]

PersonalAssistant/PersonalAssistant/Utils/urls.py
from django.urls import path
from . import views


app_name = 'utils'

urlpatterns = [
    path('upload_files/', views.upload_files, name="upload"),
    path('images/', views.show_user_images, name="show_images"),
    path('documents/', views.show_user_documents, name="show_documents"),
    path('unknown/', views.show_user_unknown, name="show_unknown"),
    path('download/<int:file_id>', views.download_user_file, name="download"),
    path('delete/<int:file_id>', views.remove_user_file, name="delete"),
    path('authorize/', views.dropbox_oauth, name='dropbox_oauth'),
    path('authorized/', views.dropbox_authorized, name='dropbox_authorized'),
    path('weather/', views.weather_forcast, name="get_weather"),
    path('utils_main_page/', views.main_page, name='main_page')
]

PersonalAssistant/PersonalAssistant/Contacts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ForeignKey
from django.core.validators import EmailValidator


class Contact(models.Model):
    
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField(validators=[EmailValidator(message="Invalid email address")])
    birthday = models.DateField()
    user = ForeignKey(User, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['name']

PersonalAssistant/PersonalAssistant/Contacts/forms.py
from django import forms
from .models import Contact
import phonenumbers


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'address', 'phone_number', 'email', 'birthday']
        exclude = ['user']

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        try:
            parsed_number = phonenumbers.parse(phone_number, None)
            if not phonenumbers.is_valid_number(parsed_number):
                raise forms.ValidationError("Invalid phone number. Please enter a valid phone number.")
        except Exception:
            raise forms.ValidationError("Invalid phone number format. Please use a valid format.")
        return phone_number


class ContactDeleteForm(forms.Form):
    pass


class FeedbackForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)

PersonalAssistant/PersonalAssistant/Contacts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .forms import ContactForm, FeedbackForm
from datetime import date
from .models import Contact
from django.core.cache import cache
from django.contrib.auth.models import User

from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options

from envelopes import Envelope

import os
import json
import requests
from ipware import get_client_ip
from dotenv import load_dotenv

load_dotenv()


def set_userdata(request, data):
    key = f"user{request.user.id}_data"
    cache.set(key, data)


def get_userdata(request):
    key = f"user{request.user.id}_data"
    return cache.get(key)


@login_required
def start_page(request):
    user_name = User.objects.get(id=request.user.id).username
    cache_key = f"user_weather_data:{request.user.id}"
    cached_data = cache.get(cache_key)
    if cached_data:
        data = json.loads(cached_data)
        city_name = data['data'][0]['city_name']
        country_code = data['data'][0]['country_code']
        wind_spd = data['data'][0]['wind_spd']
        app_temp = data['data'][0]['app_temp']
        aqi = data['data'][0]['aqi']
        temp = data['data'][0]['temp']
        context = {'city': city_name, 'country': country_code, 'wind_spd': wind_spd, 'app_temp': app_temp,
                                   'aqi': aqi, 'temp': temp, 'user_name': user_name, 'src': data['src'],
                                   'title': data['title'], 'text': data['text_'], 'href': data['href']}
        return render(request, 'Contacts/index.html', context)
    else:
        try:
            # weatherbit.io
            api_key = os.environ.get('API_WEATHER')
            client_ip, is_routable = get_client_ip(request)
            api = os.environ.get('API_IPSTACK')
            if client_ip:
                request_url = f'http://api.ipstack.com/{client_ip}?access_key={api}'
                response = requests.get(request_url)
                result = response.content.decode()
                result = json.loads(result)
                if response:
                    latitude = result.get('latitude')
                    longitude = result.get('longitude')
                    url = f'https://api.weatherbit.io/v2.0/current?lat={latitude}&lon={longitude}&key={api_key}'
                    try:
                        data = requests.get(url).json()
                        city_name = result.get('city')
                        country_code = data['data'][0]['country_code']
                        wind_spd = data['data'][0]['wind_spd']
                        app_temp = data['data'][0]['app_temp']
                        aqi = data['data'][0]['aqi']
                        temp = data['data'][0]['temp']
                        news = get_wp_last_news()
                        context = {'city': city_name, 'country': country_code, 'wind_spd': wind_spd, 'app_temp': app_temp,
                                   'aqi': aqi, 'temp': temp, 'user_name': user_name, 'src': news['src'],
                                   'title': news['title'], 'text': news['text_'], 'href': news['href']}
                        cache.set(cache_key, json.dumps(context), timeout=3600)
                    except Exception as e:
                        return HttpResponse({'status': str(e)})
                    return render(request, 'Contacts/index.html', context)
        except Exception as e:
            return HttpResponse({'status': str(e)})
    return render(request, 'Contacts/index.html')


@login_required
def add_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return redirect('contacts:contact_list')
    else:
        form = ContactForm()
    return render(request, 'Contacts/add_contact.html', {'form': form})


@login_required
def contact_search(request):
    query = request.GET.get('q')

    if query:
        results = Contact.objects.filter(name__icontains=query, user_id=request.user.id)
    else:
        results = []

    context = {
        'query': query,
        'results': results,
    }
    return render(request, 'Contacts/contact_search.html', context)


@login_required
def edit_contact(request, contact_id):
    contact = get_object_or_404(Contact, id=contact_id)

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('contacts:contact_list')
    else:
        form = ContactForm(instance=contact)

    return render(request, 'Contacts/edit_contact.html', {'form': form})


@login_required
def delete_contact(request, contact_id):
    contact = Contact.objects.get(id=contact_id)
    contact.delete()
    return redirect('contacts:contact_list')


@login_required
def contact_list(request):
    contacts = Contact.objects.filter(user_id=request.user.id)
    for contact in contacts:
        contact.days_until_birthday = days_until_birthday(contact.birthday)

    context = {
        'contacts': contacts,
    }

    return render(request, 'Contacts/contact_list.html', context)


def days_until_birthday(birthday):
    today = date.today()
    next_birthday = birthday.replace(year=today.year)
    if today > next_birthday:
        next_birthday = next_birthday.replace(year=today.year + 1)
    days_left = (next_birthday - today).days
    return days_left


def send_feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            envelope = Envelope(
                from_addr=os.environ.get("EMAIL_HOST_USER"),
                to_addr=(u'panpukhaa@gmail.com', u'To Example'),
                subject=form.cleaned_data['subject'],
                text_body=form.cleaned_data['message']
            )
            envelope.send(os.environ.get("EMAIL_HOST"), login=os.environ.get("EMAIL_HOST_USER"),
                          password=os.environ.get("EMAIL_HOST_PASSWORD"), tls=True)
            # send_mail(subject, message, sender_email, recipient_list, fail_silently=False)
            return redirect('contacts:feedback_success')
    else:
        form = FeedbackForm()

    return render(request, 'Contacts/feedback.html', {'form': form})


chrome_options = Options()
chrome_options.add_argument('--headless')
options = chrome_options


def get_wp_last_news():
    result = {}
    driver = webdriver.Chrome(options=chrome_options)
    driver.get('https://www.washingtonpost.com/')
    res_search = driver.find_elements(By.ID, 'main-content')
    find_blk = res_search[0].get_attribute('outerHTML')
    soup = BeautifulSoup(find_blk, 'html.parser')
    img = soup.find_all('div', class_="dib relative")
    for i in img:
        src = i.find('a')
        res = src.find('img')['src']
        result.update({'src': res})
        break
    links = soup.find_all('div', class_="card-left card-text next-to-art no-bottom")
    for link in links:
        title = link.find('h2').find('span').text
        text_ = link.text
        href = link.find('a', href=True)['href']
        result.update({'title': title, 'text_': text_, 'href': href})
        break
    driver.quit()
    return result

  
def feedback_success(request):
    return render(request, 'Contacts/feedback_success.html')

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/add_contact.html
{% extends "Contacts/base.html" %}

{% block content %}
<style>
    h2 {
        font-size: 24px;
        margin-bottom: 20px;
    }

    form {
        max-width: 400px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    }

    form label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
    }

    form input[type="text"],
    form input[type="email"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    button[type="submit"] {
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    button[type="submit"]:hover {
        background-color: #0056b3;
    }
</style>

<h2>Add Contact</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Contact</button>
    <a href="{% url 'contacts:contact_list' %}">Back to contacts</a>
</form>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'Contacts/style.css' %}">
    <title>PersonalAssistant</title>
</head>
<body>
    <nav class="navbar" style="background-color: lightblue;">
        <div class="container-fluid">
            <h2 class="me-auto">Personal Assistant</h2>
            <button class="btn btn-outline-success me-2" type="button"><a style='text-decoration: none; color: inherit;' href="{% url 'contacts:start_page' %}">Profile</a></button>
            <button class="btn btn-sm btn-outline-secondary" type="button"><a style='text-decoration: none; color: inherit;' href="{% url 'users:logout' %}">Logout</a></button>
        </div>
    </nav>
    <br>
    <br>
    {% block content %}
    {% endblock %}
    <footer>
        <p>&copy; 2023 <b>Dushiteli_zmei</b>. All rights reserved by intergalactic alliance.</p>
    </footer>
</body>
</html>

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/contact_list.html
{% extends "Contacts/base.html" %}

{% block content %}
<style>
    .contact-card {
        border: 1px solid #ccc;
        border-radius: 5px;
        padding: 15px;
        margin: 10px;
        display: inline-block;
        width: 300px;
    }

    h2 {
        font-size: 24px;
        margin-bottom: 20px;
        display: flex;
        align-items: center;
    }

    .action-buttons {
        margin-left: auto; /* Переместить кнопки вправо */
    }

    .action-buttons button {
        margin-left: 10px;
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        background-color: #007bff; /* Цвет кнопок */
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    .action-buttons button:hover {
        background-color: #0056b3; /* Цвет кнопок при наведении курсора */
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    li {
        font-size: 18px;
        margin-bottom: 10px;
    }

    a {
        text-decoration: none;
        color: #007bff; /* Цвет ссылки */
    }

    a:hover {
        text-decoration: underline; /* Подчеркивание ссылки при наведении курсора */
    }

    p {
        font-size: 16px;
        margin-top: 10px;
    }

    /* Стили для "No contacts found" сообщения */
    .empty-message {
        font-style: italic;
        color: #999;
    }
</style>

<h2>Contact List
    <div class="action-buttons">
        <button><a style='text-decoration: none; color: inherit;' href="{% url 'contacts:add_contact' %}">Add Contact</a></button>
        <button><a style='text-decoration: none; color: inherit;' href="{% url 'contacts:contact_search' %}">Search Contact</a></button>
    </div>
</h2>
<div>
    {% for contact in contacts %}
        <div class="contact-card">
            <ul>
                <li>
                    {{ contact.name }}
                </li>
                <li>
                    Phone: {{ contact.phone_number }}
                </li>
                <li>
                    Email: {{ contact.email }}
                </li>
                <li>
                    Days left to birthday: {{ contact.days_until_birthday }} days
                </li>
            </ul>
            <p><a href="{% url 'contacts:edit_contact' contact.id %}">Edit</a></p>
            <p><a href="{% url 'contacts:delete_contact' contact.id %}">Remove</a></p>
        </div>
    {% empty %}
        <div class="empty-message">No contacts found</div>
    {% endfor %}
</div>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/contact_search.html
{% extends "Contacts/base.html" %}

{% block content %}
<style>
    h2 {
        font-size: 24px;
        margin-bottom: 20px;
    }

    form {
        max-width: 400px;
        margin-bottom: 20px;
    }

    input[type="text"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    button {
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #0056b3;
    }

    h3 {
        font-size: 20px;
        margin-bottom: 10px;
    }

    ul {
        list-style-type: none;
        padding: 0;
    }

    li {
        font-size: 18px;
        margin-bottom: 10px;
    }

    /* Стили для "No results found" сообщения */
    .empty-message {
        font-style: italic;
        color: #999;
    }
</style>

<h2>Contact Search</h2>
<form method="get">
    <input type="text" name="q" value="{{ query }}" placeholder="Search contacts">
    <button type="submit">Search</button>
</form>

<h3>Search Results for "{{ query }}"</h3>
<ul>
    {% for contact in results %}
        <li>{{ contact.name }} - {{ contact.email }} - {{ contact.phone_number }}</li>
    {% empty %}
        <li class="empty-message">No results found</li>
    {% endfor %}
</ul>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/edit_contact.html
{% extends "Contacts/base.html" %}

{% block content %}
<style>
    h2 {
        font-size: 24px;
        margin-bottom: 20px;
    }

    form {
        max-width: 400px;
        padding: 20px;
        border: 1px solid #ccc;
        border-radius: 5px;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
    }

    form label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
    }

    form input[type="text"],
    form input[type="email"] {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        border: 1px solid #ccc;
        border-radius: 5px;
    }

    form button {
        padding: 10px 15px;
        border: none;
        border-radius: 5px;
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    form button:hover {
        background-color: #0056b3;
    }

    a {
        text-decoration: none;
        color: #007bff;
    }

    a:hover {
        text-decoration: underline;
    }
</style>

<h2>Edit Contact</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
    <a href="{% url 'contacts:contact_list' %}">Back to contacts</a>
</form>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/feedback.html
{% extends "Contacts/base.html" %}

{% block content %}
    <h1>FeedBack</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/feedback_success.html
{% extends "Contacts/base.html" %}
{% block content %}
    <h1>Your feedback has been sent successfully!</h1>
    <p>Thank you for your message. We will contact you shortly.</p>
{% endblock %}

PersonalAssistant/PersonalAssistant/Contacts/templates/Contacts/index.html
{% extends "Contacts/base.html" %}

{% block content %}
    <style>
        /* CSS для центрирования текста по верхней горизонтали */
        .top-center {
            position: absolute;
            top: 2;
            left: 50%;
            transform: translateX(-50%);
        }
        .centered {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
    </style>

    <div>
        <h4 class="top-center mt-5">Hello, <i>{{ user_name }}</i>. It's your profile</h4>
    </div>

    <div class="centered">
        <div class="example">
            <img src="{{ src }}" alt="image">
            <h3>{{ title }}</h3>
            <p>{{ text_ }}</p>
            <p>Sourse: <a href="{{ href }}">...</a></p>
        </div>
    </div>

    <div class="position-absolute top-0 end-0 mt-5 me-3">
        <div class="container mt-5">
            <h4><a href="{% url 'utils:get_weather' %}" style="text-decoration: none; color: inherit;">Weather</a></h4>
            <table class="table">
                <tbody>
                    <tr>
                        <th>City: </th>
                        <td>{{ city }}</td>
                    </tr>
                    <tr>
                        <th>County: </th>
                        <td>{{ country }}</td>
                    </tr>
                    <tr>
                        <th>Temperature: </th>
                        <td>{{ temp }}&deg;C</td>
                    </tr>
                    <tr>
                        <th>Feels like: </th>
                        <td>{{ app_temp }}&deg;C</td>
                    </tr>
                    <tr>
                        <th>Air Quality Index: </th>
                        <td>{{ aqi }}</td>
                    </tr>
                    <tr>
                        <th>Wind speed: </th>
                        <td>{{ wind_spd }} m/s</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'contacts:contact_list' %}">
      <div class="card-body">
        <h5 class="card-title">Contacts</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">ContactBook</h6>
        <p class="card-text">Click here to view and manage contacts</p>
      </div>
      </a>
    </div>
    <br>

    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'notes:index' %}">
      <div class="card-body">
        <h5 class="card-title">Notes</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">NoteBook</h6>
        <p class="card-text">Click here to view and manage notes and tags</p>
      </div>
      </a>
    </div>

    <br>
    <div class="card" style="width: 18rem;">
      <a class="nav-link active" href="{% url 'utils:main_page' %}">
      <div class="card-body">
        <h5 class="card-title">Files</h5>
        <h6 class="card-subtitle mb-2 text-body-secondary">Images/Documents/Another</h6>
        <p class="card-text">Click here to view, add, or download your files</p>
      </div>
      </a>
    </div>


{% endblock %}